### ISSUE TITLE
Zvažte použití python enviroment

### ISSUE THREAD

**Issue by karellat** [opendatalabcz/isir-explorer#1]
Možná by stálo používat pro instalaci nějakou formu python enviromentu.
* https://virtualenv.pypa.io/en/latest
* https://docs.conda.io/en/latest/miniconda.html
* https://github.com/pyenv/pyenv

**Comment by tumapav** [comment]
Využití venv jsem nyní přidal do doporučeného postupu pro instalaci.

**Comment by karellat** [comment]
Super 👍
